/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// #include "Mozzi/examples/01.Basics/Sinewave/Sinewave.ino"        // nice and smooth
// #include "Mozzi/examples/01.Basics/Vibrato/Vibrato.ino"         // sounds good vibrato
// #include "Mozzi/examples/06.Synthesis/Detuned_Beats_Wash/Detuned_Beats_Wash.ino" // great organ? vibes


#include "Mozzi/examples/02.Control/Control_Echo_Theremin/Control_Echo_Theremin.ino" // sounds spacy theremin
// #include "Mozzi/examples/02.Control/Control_Oscil_Wash/Control_Oscil_Wash.ino" // sounds good
// #include "Mozzi/examples/07.Envelopes/ADSR_Audio_Rate_Envelope/ADSR_Audio_Rate_Envelope.ino" // Geigenschüler

// #include "Mozzi/examples/10.Audio_Filters/LowPassFilterX2/LowPassFilterX2.ino"

// #include "Mozzi/examples/02.Control/Line_Gliss/Line_Gliss.ino" // saw teeth, sounds wrong
// #include "Mozzi/examples/06.Synthesis/Brown_Noise_Realtime/Brown_Noise_Realtime.ino" // pouring rain
// #include "Mozzi/examples/06.Synthesis/PWM_Phasing/PWM_Phasing.ino" // fat sound, but boring

// #include "Mozzi/examples/09.Delays/AudioDelay/AudioDelay.ino"   // mistuned

#include <sysclk.h>

int main(void)
{
    sysclk_init_hsi_80();

    setup();

    /* Loop forever */
 	for(;;) {
        loop();
    };
}
